### PR TITLE
Expand macros

### LINKED ISSUE #9: Bad interaction with `@.` macro
`@changeprecision Float64 @. 3 + [1. 2.]` gives `ERROR: MethodError: no method matching +(::Int64, ::Array{Float64,2})`

### PR DESCRIPTION
**Pull request by antoine-levitt**
Fixes https://github.com/stevengj/ChangePrecision.jl/issues/9.
Not completely sure if that is the correct thing to do, but that does seem to fix it.

### CODE REVIEW

File: src/ChangePrecision.jl [hunk 1]
```diff
@@ -85,7 +85,9 @@ function changeprecision(T, x::Float64)
     end
 end
 function changeprecision(T, ex::Expr)
-    if Meta.isexpr(ex, :call, 3) && ex.args[1] == :^ && ex.args[3] isa Int
+    if Meta.isexpr(ex, :macrocall)
+        return changeprecision(T, macroexpand(ChangePrecision, ex))
```
Comment (stevengj) [inline src/ChangePrecision.jl]: This isn't right — if anything, we would want to expand in the caller's module.

Comment (antoine-levitt) [reply src/ChangePrecision.jl]: So just `macroexpand(@__MODULE__, ex)`?

Comment (stevengj) [reply src/ChangePrecision.jl]: Note that the caller's module is passed to the `@changeprecision` macro as `__module__`, so from there it can be passed to the `changeprecision` function.

Comment (antoine-levitt) [reply src/ChangePrecision.jl]: So it has to be passed downstream to every `changeprecision` method? Should `include` also do this?

Comment (stevengj) [reply src/ChangePrecision.jl]: Yes, it has to be passed downstream through every method.

Comment (antoine-levitt) [reply src/ChangePrecision.jl]: See last commit

**Comment by stevengj** [comment]
Note that the basic reason why the `@.` macro doesn't work as-is is that we interpolate the transformed function, e.g. `ChangePrecision.+`, directly into the expression (as a function value, not as a symbol), and the `@.` uses interpolated function values as an indication that the user didn't want to broadcast that call.

File: src/ChangePrecision.jl (hunk 1 above)
Comment (stevengj) [reply src/ChangePrecision.jl]: Upon reflection, I'm not sure this will be the right thing, e.g. if the user evaluates a module definiton.

File: src/ChangePrecision.jl [hunk 2]
```diff
@@ -84,19 +84,21 @@ function changeprecision(T, x::Float64)
         return :(parse($T, $(string(x))))
     end
 end
-function changeprecision(T, ex::Expr)
-    if Meta.isexpr(ex, :call, 3) && ex.args[1] == :^ && ex.args[3] isa Int
+function changeprecision(T, ex::Expr, mod)
+    if Meta.isexpr(ex, :macrocall)
```
Comment (stevengj) [inline src/ChangePrecision.jl]: Maybe we should just expand the `@.` macro, i.e. only expand a macrocall to `__dot__`?   To do that without expanding other nested macros, we would have to do something like:
```jl
if Meta.isexpr(ex, :macrocall) && ex.args[1] == Symbol("@__dot__")
    return changeprecision(T, Base.Broadcast.__dot__(ex.args[end]))
```
```

Comment (antoine-levitt) [reply src/ChangePrecision.jl]: That is more surgical, but things like `@..` (that DiffEq uses and that has a few more bells and whistles on top of `@.`) won't work. I'm fine with whatever.

Btw, is
```julia
elseif Meta.isexpr(ex, :call, 3) && ex.args[1] == :^ && ex.args[3] isa Int
else
```
a typo?

Comment (stevengj) [reply src/ChangePrecision.jl]: whoops, looks like I was trying to do something special for literal powers but forgot to fill it in?

Comment (stevengj) [reply src/ChangePrecision.jl]: Ultimately, it's hard to do something completely reliable here… ChangePrecision is meant for quick hacks and experiments, not for long-term usage.    I'd prefer to err on the side of narrower transformations, though, even if it fails noisily in some cases.

Comment (antoine-levitt) [reply src/ChangePrecision.jl]: OK, done
